apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mikapp1
  name: mikapp1
  namespace: mik-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mikapp1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mikapp1
    spec:
      containers:
      - image: dockerashu/ashumobi:appv1
        name: ashumobi
        ports:
        - containerPort: 80
        resources: {}
        imagePullPolicy: Always

        
## adding service with nodeport   
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: miksvc1
  name: miksvc1
  namespace: mik-project
spec:
  ports:
  - name: 1233-80
    port: 1233
    protocol: TCP
    targetPort: 80
  selector: # need to match label of pods 
    app: ashuapp1
  type: NodePort
status:
  loadBalancer: {}
